name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,h} ! -name '*ctest.h' | xargs clang-format --style google -i --verbose && git diff --exit-code

      - name: Build application
        run: make

      - name: Build test
        run: make test

      - name: Test run
        run: make run_test
        